### ISSUE TITLE
Function-based interface versus object-oriented approach

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto_prototype#10]
Dear clesperanto-fans, dear future self,

at the moment, we're using [static functions](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/clesperanto/plugins/__init__.py) to call operations. The GPU device selection is global and transparent. In a normal user-scenario, we don't event know what GPU is selected by gputools. In CLIJ2, all operations sit in a [code-generated interface](https://github.com/clij/clij2/blob/master/src/main/java/net/haesleinhuepf/clij2/CLIJ2Ops.java) that's attached to an CLIJ2-instance which allows us to have several instances executing operations in parallel on several GPUs. We may have to switch to a similar approach in clEsperanto.

Cheers,
Robert

**Comment by jni** [comment]
Why are instances required as opposed to eg a `_device=` keyword argument?

**Comment by haesleinhuepf** [comment]
Both would work. Actually, both is implemented in [CLIJ2](https://github.com/clij/clij2/blob/master/src/main/java/net/haesleinhuepf/clij2/plugins/AddImages.java#L27). All operations exist as static methods can can be called with a CLIJ(2) instance. I'm not advertising this as public API for two reasons: Auto-completion allows you to browse available methods if you start from the clij2.gateway. You know discovering what operations are there is the major problem for both beginners and experts ;-)
![image](https://user-images.githubusercontent.com/12660498/83752022-1c4f7380-a668-11ea-843e-107df450f0c0.png)

Furthermore, it's intuitive to call and see that everyting happens in "clij2":
```
a = clij2.push()
clij2.process(a, b)
clij2.pull(b)
```

Background is, you cannot process images on one device which were pushed to another. This would crash in the last line:
```
clijA = CLIJ2("rtx")
clijB = CLIJ2("gtx")

imageA = clijA.push(image_cpu)
imageB = clijB.create(imageA)

clijA.absolute(imageA, imageB)
```

Btw. in general, I would love to dynamically distribute tasks between GPUs, but various approaches failed... It boils down to the end-user who makes the decision on which device to do what.

**Comment by haesleinhuepf** [comment]
To make this clear: I would be happy to have both approaches available to end-users. They should decide what they like most. I actually love to do code like this:
```
import cleasperanto as cle
cle.operation(...)
```

It's very beautiful and simple in contrast to
```
import clesperanto
cle = clesperanto.getInstance()

cle.operation()
```

**Comment by jni** [comment]
> You know discovering what operations are there is the major problem for both beginners and experts

But this works totally fine for modules in Python?

```python
from skimage import segmentation
segmentation.<TAB>
```

will give you all the methods in the segmentation module. 

Re buffer locations, I think that should be an attribute on the OCLArray rather than something to do with the instance calling the function.

**Comment by haesleinhuepf** [comment]
> But this works totally fine for modules in Python?

Sure, but not in ImageJ ;-) I'm just explaining why we did it how we did it in ImageJ. Discovering operations there is a real issue.


> Re buffer locations, I think that should be an attribute on the OCLArray rather than something to do with the instance calling the function.

Agreed. I already see clEsperanto will become much better than clij ever was; on python and on the java side :-)

**Comment by haesleinhuepf** [comment]
[Citing](https://github.com/clEsperanto/pyclesperanto_prototype/pull/27/files#diff-94e3ef33f8614e88ecf2f7574a4a3046R11-R12) @tlambert03 

> TODO: we should discuss whether this collection is actually the best thing to pass around. might be better to work lower level with contexts...

This aspect is relevant here. I had to think about that two years ago and it lead to the [god-class](https://en.wikipedia.org/wiki/God_object) [CLIJ2](https://github.com/clij/clij2/blob/master/src/main/java/net/haesleinhuepf/clij2/CLIJ2.java). From a user perspective it's great, but other framework developers told me it's very bad. Not exactly sure why.

So, I would vote for having a `Device` class which owns the context. `OCLArray`s and `OCLProgram`s might then keep a reference to `Device`. We could basically live with the `cl-context`, however, if we need another convenience method in there, we have to make that change in pyopencl. Thus, I would introduce this `Device` as a defense-layer against pyopencl. And there comes the question: Should `Device` hold the `execute` method? How about `push` and `pull`?

I see two major options:
```
device = Device("NVidia")

gpu_input = device.push(image)

gpu_result = device.blur(gpu_input)

result = device.pull(gpu_result)
```

```
device = Device("NVidia")

gpu_input = push(image, device=device)

gpu_result = blur(gpu_input) # in order to make this work, gpu_input must hold a reference to device 

result = pull(gpu_result) # same here
```

Is there maybe a third option I don't see at the moment?

**Comment by jni** [comment]
@haesleinhuepf it has been on my to-do to reply to this since forever, but right now I only have time for the first thing:

> it lead to the god-class CLIJ2. From a user perspective it's great, but other framework developers told me it's very bad. Not exactly sure why.

If I understand correctly, you have a single class that is aware of everything in your program. This is equivalent to using global variables for everything. My C teacher at university trained the whole class to answer:

Teacher: "Globals are...?"
Whole class: "Baaaaaaaad."

20 years later I still have the reflex. =D

So why is it bad? Because it violates locality: the behaviour of code should only depend on the surrounding code, and not some global state. The converse results in difficult to debug code because something happening in some far-off part of the program can change the behaviour of the bit of code you're trying to debug, and you have no way of knowing where/when/how/why this is happening. If you have any concurrent code, that can happen *between lines of code* and then you are really screwed.

So that's why I really like functional programming, if you want to debug what a function is doing, you look at the inputs and follow the function down, and you don't have to worry about *why* `self.whatever` is set to True and not False since you're *sure* it should be False, but actually some other part of the code changed it before you got here, but *which* part?

I'm getting cold sweats just writing that. LOL

Anywho, hopefully that clarifies my stance on object oriented stuff. =)

**Comment by haesleinhuepf** [comment]
> code should only depend on the surrounding code, and not some global state

Hm, I think CLIJ2 is fine in this aspect. The "state" in the CLIJ2 class is basically just the opencl-context, the pointer to the GPU. It's a singleton implementation, hence per default you have one GPU and the link to it is kind of saved in a global variable. I think that's fine. We have a [similar implementation](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/pyclesperanto_prototype/_tier0/_pycl.py#L44) in pyclesperanto at the moment. The actual methods in CLIJ2 don't have side effects and CLIJ2 hardly has any member variables. The god class thingy is just a convenience thing: CLIJ2 has a (code-generated) [list](https://github.com/clij/clij2/blob/master/src/main/java/net/haesleinhuepf/clij2/CLIJ2Ops.java#L362-L6600) of all methods. I basically implemented that to make auto-completion of methods work. In Python there might be [better ways](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/pyclesperanto_prototype/__init__.py) of doing this.




> Anywho, hopefully that clarifies my stance on object oriented stuff. =)

Hehe. I'm afraid we can't avoid it when it comes to multi-gpu support. ;-)
