### ISSUE TITLE
Runtime Warning for statistics_of_labelled_pixels function

### ISSUE THREAD

**Issue by lcferme** [clEsperanto/pyclesperanto_prototype#108]
Hello :)

I was trying to extract some statistics from some segmented stacks using statistics_of_labelled_pixels and I got this RuntimeWarning:

`/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyclesperanto_prototype/_tier9/_statistics_of_labelled_pixels.py:176: RuntimeWarning: overflow encountered in subtract
  bbox_max_z - bbox_min_z + 1,
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyclesperanto_prototype/_tier9/_statistics_of_labelled_pixels.py:177: RuntimeWarning: overflow encountered in subtract
  bbox_max_y - bbox_min_y + 1,
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyclesperanto_prototype/_tier9/_statistics_of_labelled_pixels.py:178: RuntimeWarning: overflow encountered in subtract
  bbox_max_x - bbox_min_x + 1,
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyclesperanto_prototype/_tier9/_statistics_of_labelled_pixels.py:180: RuntimeWarning: overflow encountered in subtract
  region_props['bbox_width'] = bbox_max_x - bbox_min_x + 1
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyclesperanto_prototype/_tier9/_statistics_of_labelled_pixels.py:181: RuntimeWarning: overflow encountered in subtract
  region_props['bbox_height'] = bbox_max_y - bbox_min_y + 1
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyclesperanto_prototype/_tier9/_statistics_of_labelled_pixels.py:182: RuntimeWarning: overflow encountered in subtract
  region_props['bbox_depth'] = bbox_max_z - bbox_min_z + 1`

Is there a way to avoid this, for instance by specifying the dtype? 

Cheers!
Lucrezia

**Comment by haesleinhuepf** [comment]
Hi Lucrezia @lcferme ,

thanks for the report! I agree, we should avoid warnings of that kind if possible.

I'm not sure (yet) in which scenario / why this warning comes up. Would you mind trying something for me? I presume the label image you're processing has "gaps", e.g. label number 4 doesn't exist in the label image.

You can close those gaps by calling
```
labels = cle.close_index_gaps_in_label_map(labels)
```

Would you mind checking if that makes the warning go away?

Thanks!
Robert

**Comment by lcferme** [comment]
Yes, it worked! 
Curiosity from a newbie: how does it come that you can detect the label in the image but then this label does not actually exist in the image? 

Cheers, 
Lucrezia

**Comment by haesleinhuepf** [comment]
> Curiosity from a newbie: how does it come that you can detect the label in the image but then this label does not actually exist in the image?

This should actually not happen. Do you `shrink_labels`? If a label is one pixel thick and you shrink it, it's gone :-)
