### ISSUE TITLE
Have all methods accepting "either NumPy-coercible or OpenCL buffers" as image inputs

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto_prototype#117]
Hi @jni ,

that's an idea from you. At the moment, `cle.whatever(image)` accepts numpy-arrays or OpenCL arrays. (see details [here](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/pyclesperanto_prototype/_tier0/_plugin_function.py#L64) and [here](https://github.com/clEsperanto/pyclesperanto_prototype/blob/4bff456f870e19363e396768de1466cdc772302c/pyclesperanto_prototype/_tier0/_types.py#L8))

At the moment, `cle.push(cuda_image)` fails. Do you know how I can ask if a variable is numpy-array-able? Of course, I'd like to do that without importing cupy  in clesperanto.

Thanks!
Robert

Example code:
```
import numpy as np
from skimage.io import imread, imshow
image = np.asarray([[1, 2, 3]])

import cupy
cuda_image = cupy.asarray(image)

import pyclesperanto_prototype as cle
cle.push(cuda_image)
```

Output:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-95cfc3c115d2> in <module>
      7 
      8 import pyclesperanto_prototype as cle
----> 9 cle.push(cuda_image)
     10 

c:\structure\code\tl_pyclesperanto_prototype\pyclesperanto_prototype\_tier0\_push.py in push(any_array, dtype)
     35 
     36     _arr = any_array.astype(np.float32 if dtype is None else dtype)
---> 37     return OCLArray.from_array(_arr)
     38 
     39 

c:\structure\code\tl_pyclesperanto_prototype\pyclesperanto_prototype\_tier0\_pycl.py in from_array(cls, arr, *args, **kwargs)
    250         assert_supported_ndarray_type(arr.dtype.type)
    251         queue = get_device().queue
--> 252         return array.to_device(queue, prepare(arr), *args, **kwargs)
    253 
    254     @classmethod

c:\structure\code\tl_pyclesperanto_prototype\pyclesperanto_prototype\_tier0\_pycl.py in prepare(arr)
    244 
    245     def prepare(arr):
--> 246         return np.require(arr, None, "C")
    247 
    248     @classmethod

~\miniconda3\envs\bio2\lib\site-packages\numpy\core\_asarray.py in require(a, dtype, requirements)
    314         requirements.remove('C')
    315 
--> 316     arr = array(a, dtype=dtype, order=order, copy=False, subok=subok)
    317 
    318     for prop in requirements:

cupy\_core\core.pyx in cupy._core.core.ndarray.__array__()

TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.

```

**Comment by haesleinhuepf** [comment]
Addendum (potentially note to self):

The opposite direction works
```
import numpy as np
from skimage.io import imread, imshow
image = np.asarray([[1, 2, 3]])

import pyclesperanto_prototype as cle
cle_image = cle.push(image)

import cupy
cupy.asarray(cle_image)
```

Thus, the cupy folks have the solution for that problem.

**Comment by tlambert03** [comment]
when you call [`cupy.asarray(obj)`](https://github.com/cupy/cupy/blob/24ff37b01b8d4df6c4f78c38398f52eea866f2ad/cupy/_creation/from_data.py#L44-L66), it's calling `cupy._core.array(obj)` behind the scenes (cython constructor [here](https://github.com/cupy/cupy/blob/24ff37b01b8d4df6c4f78c38398f52eea866f2ad/cupy/_core/core.pyx#L2126)).  If you're curious to see how they handle generic objects, it's [here](https://github.com/cupy/cupy/blob/24ff37b01b8d4df6c4f78c38398f52eea866f2ad/cupy/_core/core.pyx#L2159-L2194)... basically anything that has a `.shape` and a `.dtype` (which pyopencl.Array does) will work
