### ISSUE TITLE
flip = cli.push example fails

### ISSUE THREAD

**Issue by tlambert03** [clEsperanto/pyclesperanto_prototype#12]
hey @haesleinhuepf,

I"m confused how this first example in your readme and your test would ever work:
`cle.push(np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20]))`

these lines in `push.py` say that if the array is not 2D, call `np.swapaxes(temp, 0, 2)`
https://github.com/clEsperanto/pyclesperanto_prototype/blob/858983f5165e30b761238e022e30262d586f9878/clesperanto/core/push.py#L22-L25

but calling `np.swapaxes` on a 1D array with `axis2=2` throws `AxisError: axis2: axis 2 is out of bounds for array of dimension 1`.  Should the example be a 2D array instead?

**Comment by haesleinhuepf** [comment]
Good point @tlambert03 ! 

Obviously, I need to keep the examples up to date. [Here](https://gist.github.com/haesleinhuepf/8ebd1a7233c201ad78d501a0be12efc5)'s the current version. Basically there is just a bracket missing to make it a 2D array as you suggested:
cle.push(np.array([[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]]))

That's an artifact from CLIJ: CLIJ doesn't support 1-D images (API design failure on my side). We should (and will) change that in future releases.
