### ISSUE TITLE
Inversion operation in cle.equal_constant?

### ISSUE THREAD

**Issue by jo-mueller** [clEsperanto/pyclesperanto_prototype#135]
Hi,

I am having an issue with ```cle.equalConstant```, which I use to create masks from labeled images like this:
```python
mask = cle.equal_constant(img == 1)
```

However, the produced output of said function is the inverse of what I would expect from the ouput. 

### Steps to reproduce
```python
import numpy as np
import matplotlib.pyplot as plt
import pyclesperanto_prototype as cle

# create example image
img = np.zeros((100,100))
img[25:75, 25:75] = 1

# Push to GPU and apply operation
_img = cle.push(img)
mask_cle = cle.equal_constant(_img == 1)
mask_np = img == 1

plt.figure()
plt.imshow(mask_cle)
plt.title('cle')

plt.figure()
plt.imshow(1*mask_np)
plt.title('np')
```

This snippet creates these two images:
![Figure_1](https://user-images.githubusercontent.com/38459088/138688364-e311e583-2f4d-4dbf-ae5b-75ed5a20174a.png)
![Figure_2](https://user-images.githubusercontent.com/38459088/138688366-ac25e64b-431f-435b-bffe-086282a3e536.png)

Best, Johannes

**Comment by haesleinhuepf** [comment]
Hi Johannes @jo-mueller ,

is your issue resolved? Can I close this here?

Thanks for the feedback!

Best,
Robert
