### ISSUE TITLE
Affine-transform auto-size API convenience

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto_prototype#167]
To make the auto-size feature for affine transforms easier to use, we should make this function publicly available and give it a better name:

```
cle._tier8._affine_transform._determine_translation_and_bounding_box
```

Maybe something like

```
AffineTransform3D.auto_size()
```

**Comment by pr4deepr** [comment]
We are finding the bounds of the coordinate system in the transformed image and translating the image to keep within the new coordinate system. So, would something like `auto_bounds` make sense? or `keep_in_bounds`?

**Comment by haesleinhuepf** [comment]
I'm thinking of splitting it into two functions: One function that makes sure the output image lies in positive coordinate system. And another function that tells us how large the resultimg image would have to be. That might be cleaner. I also think it makes sense to think a bit about and do it with a later release...
