### ISSUE TITLE
__getitem__ and ellipsis

### ISSUE THREAD

**Issue by tlambert03** [clEsperanto/pyclesperanto_prototype#177]
heads up, saw the following error from napari-error-reporter:

when indexing into an array from pyclesperanto:
```py
  layer.data[:, y_ind, ...]
``` 

```python
  File "pyclesperanto_prototype/_tier0/_array_operators.py", line 305, in __getitem__
    result = range(self, start_x=x_range.start, stop_x=x_range.stop, step_x=x_range.step,
```

might want to also check for indexing with ellipsis and either try to support it, or raise a NotImplementedError

**Comment by haesleinhuepf** [comment]
Thanks for reporting @tlambert03 ! It's a fantastic proof that the napari-error-reporter works 🥳 
A fix should also be possible very soon. 

Thanks again!
