### ISSUE TITLE
Image path to reproduce some benchmark.

### ISSUE THREAD

**Issue by JoOkuma** [clEsperanto/pyclesperanto_prototype#183]
Hello,

Where can I find the image to reproduce the `deskweing.ipynb` benchmark?

@pr4deepr

**Comment by haesleinhuepf** [comment]
Pradeep @pr4deepr Jordao is right, there's a hardcoded path (E:/Py...) in this notebook: https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/benchmarks/deskewing.ipynb

Would it make sense to run the benchmark on a smaller file (from the ../data folder) or shall we use `np.ones(shape)` to create a realistic use-case scenario? You deskew more often than I do. Looking forward to hear what you think!

**Comment by pr4deepr** [comment]
Ahh, sorry about that. I'll upload the dataset (~100MB) and update the notebook as well. .

Nice to meet you @JoOkuma ...

**Comment by pr4deepr** [comment]
I think its nice to have real data, as you can visualise the cells/objects in the field of view after deskewing. Gives an indication if anything went wrong. 
However, if the dataset folder is getting too big, can always change to `np.ones(shape)` in the future.

**Comment by haesleinhuepf** [comment]
Can you share the dataset you used @pr4deepr ? I think it's too big for github, so zenodo might be a way to go... Thanks!

**Comment by pr4deepr** [comment]
oops, I"ve already pushed it. 
Is that ok?

**Comment by pr4deepr** [comment]
https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/data/RBC_1_timepoint.tif

**Comment by haesleinhuepf** [comment]
Awesome, thanks @pr4deepr ! Thus, we can close this issue. 

I may move these large datasets to another place at some point an update the notebook again.

**Comment by pr4deepr** [comment]
Agree, I think downloading the data from zenodo (for example) maybe a good idea for larger datasets..

**Comment by haesleinhuepf** [comment]
We could also use this repository until it's "full":
https://github.com/clEsperanto/clesperanto_example_data
