### ISSUE TITLE
project structure & tiers

### ISSUE THREAD

**Issue by tlambert03** [clEsperanto/pyclesperanto_prototype#21]
I really like the concept of tiers for cl kernels that was introduced in #19 (wherein higher tiers depend on lower tiers), but I find it confusing that core python tools (that used to be in core) are now in `_tier0`... and I think a newcomer to the package might also be a little confused about where to start looking around.

I would support bringing the core pyclesperanto back into `pyclesperanto_prototype/core` and leave all of the `_tier*` folders as cl kernels.  Another reason for this is static analysis.  If you wanted to automatically get a list of kernels here, you used to be able to glob the plugins folder.  Now you need to do a special "glob-but-not-tier0-which-isn't-actually-kernels".

you might even put all the kernels in a top level folder... Basically, some kind of root structure that you can walk, and can easily reuse in any of the languages (without tier0 having to change its contents)
```
clesperanto
├── pycore
│   ├── __init__.py
│   ├── execute.py
│   └── ....py
├── kernels
│   ├── _tier0
│   │   ├── absolute_2d.cl
│   │   └── *.cl
│   ├── _tier1
│   │   ├── *.cl
│   │   └── ...

**Comment by haesleinhuepf** [comment]
Hm, that sounds good actually. Just one aspect which may change you opinion again, potentially: In the current scheme, only one tier (tier1 currently, tier0 in your suggestion) will have .cl files...

**Comment by tlambert03** [comment]
yeah, I noticed that ... but there will be more in the future right?  If not, then i guess it's kind going back to the core/plugins layout huh?

**Comment by haesleinhuepf** [comment]
I had an issue earlier with circular dependencies while they were all in one folder, thus I split them into core and plugins: You cannot have one __init__.py which lists
 a, b and c if b depends on c and c depends on a. They have to come in a specific order. Later I realized that this issue will happen again on higher level. I thought introducing this hierarchy resolves that... Maybe it's just a temporary thing until they are all translated...

**Comment by tlambert03** [comment]
ahhh, I see.  ok, lemme play around with it.  there's usually a good solution to circular dependencies, but I need to get the problem locally first.

**Comment by haesleinhuepf** [comment]
It's been a while... I think the problem comes back when you move [this one](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/pyclesperanto_prototype/_tier1/execute_separable_kernel.py) to tier0. It is actually some kind of core method but causes problems down there...

**Comment by tlambert03** [comment]
aha.  well, a "cheater" method for fixing circular imports is to move the import inside the function body, so if it's just that one function, this would most likely work (and probably don't need them all to be in the body)

```python
def execute_separable_kernel(...):
    from pyclesperanto_prototype._tier0.create import create
    from pyclesperanto_prototype._tier1 import copy
    from pyclesperanto_prototype._tier0.execute import execute
    from .set import set
    ...
```

**Comment by haesleinhuepf** [comment]
So this hint is really helpful. I just hit a case where an operation on tier0 (create a pointlist from a label map) needs one from tier2... So maybe this tier-idea is really not solving anything,..

**Comment by tlambert03** [comment]
If it was just there to avoid circular imports I agree.  If it was there to help mentally organize increasing layers of complexity and dependence, I don’t mind it.  But perhaps it can come later (if the only immediate application was fixing circular imports)

**Comment by haesleinhuepf** [comment]
Finding a good hierarchy for such a collection of operations is tricky. So tricky that I didn't structure them at all in clij ;-) I regret it a bit, but never found right strategy for structuring.

**Comment by tlambert03** [comment]
Yeah, seems like it would be more of a graph than a tree

**Comment by haesleinhuepf** [comment]
@tlambert03 I'm reviving this thread from your side note in #42 

> (sidenote: I want to get back to the discussion of package structure someday! :) I love the tier system for clarifying cl kernel dependencies ... but not as much for the core python code that ties it all together)

Yeah, I would also love to have a better solution. The tiers were introduced so that I don't feel lost between the hundreds of files in a folder (as in CLIJ2). Since I learned that you can have import statements in methods (for a Java developer that's mind blowing ;-) ) we can definitelty clean that up. Any better suggestion is appreciated.
