### ISSUE TITLE
Add function to cle.statistics_of_labelled_neighbors

### ISSUE THREAD

**Issue by lcferme** [clEsperanto/pyclesperanto_prototype#220]
Hello, 

I find the table that cle.statistics_of_labelled_neighbors returns extremely useful to define relations between objects in an image and I would like to know if it would be possible to integrate an additional set of values to the resulting table. So far I have defined the neighbours as the objects touching the object of interest. Since the type of objects I study do not touch each other normally, I have to dilate their boundaries by a certain range.

Would it be possible to measure the following properties for touching neighbours obtained after different number of dilations? And would it then be possible to give the number of dilations? 
- touching_neighbor_count, 
- minimum_distance_of_touching_neighbors, 
- average_distance_of_touching_neighbors, 
- maximum_distance_of_touching_neighbors, 
- max_min_distance_ratio_of_touching_neighbor
- touch_count_sum
- minimum_touch_count
- maximum_touch_count
- minimum_touch_portion
- maximum_touch_portion

Thank you!
Best,
Lucrezia

**Comment by haesleinhuepf** [comment]
Awesome! Great idea @lcferme 🌞

This will happen soon 🚀

**Comment by haesleinhuepf** [comment]
Hey Lucrezia @lcferme ,

I implemented your proposal in pyclesperanto_prototype 0.19.4. A very basic example is available in this notebook:

https://github.com/clEsperanto/pyclesperanto_prototype/blob/a04c65a76f21bad994ad7481e2bf68d757ff2194/demo/neighbors/statistics_of_dilated_neighbors.ipynb

Let me know if it works for you!

Best,
Robert
