### ISSUE TITLE
try to make sure tests pass before merging

### ISSUE THREAD

**Issue by tlambert03** [clEsperanto/pyclesperanto_prototype#24]
#22 added automatic testing (that were [passing](https://github.com/clEsperanto/pyclesperanto_prototype/actions/runs/172892676)) that runs on github each time someone submits. but #23 got merged before fixing the [tests that broke](https://github.com/clEsperanto/pyclesperanto_prototype/actions/runs/172904432).  One of the really nice things about having automated tests is that you can make sure that master is in a consistent, "working" order... while experimentation goes on in PRs and branches.

In the PR tab, you'll see the tests that run each time a new commit is pushed, so it's easy to check before merge 🎉

**Comment by haesleinhuepf** [comment]
Apologies.  😟 I'm on it.

**Comment by tlambert03** [comment]
no need to apologize! :)
if you haven't used github actions before, note that you can click on the exact failing test:
<img width="341" alt="Screen Shot 2020-07-17 at 12 25 41 PM" src="https://user-images.githubusercontent.com/1609449/87809026-b2121d00-c828-11ea-9c7e-f779b693d766.png">

and then click on the test step dropdown to see exactly what is failing:
![image](https://user-images.githubusercontent.com/1609449/87809066-bb9b8500-c828-11ea-9d5a-538accb9ed19.png)

**Comment by haesleinhuepf** [comment]
Thanks - that's indeed all new to me. I'm just used to `mvn deploy` complaining :-)
