### ISSUE TITLE
imshow() method doesn't display colorbar for images in subplots

### ISSUE THREAD

**Issue by somas193** [clEsperanto/pyclesperanto_prototype#247]
Currently the imshow() method is not able to display colorbars for images in a subplot, even after setting colorbar=True in the imshow() method, for a particular image in the subplot. This is because the code references the axes variable (instead of referencing the figure variable, which is not even passed to the imshow() method) and calls the colorbar() method on it.

**Comment by haesleinhuepf** [comment]
Hi @somas193 ,

thanks for the report! I agree, we should fix this.

> instead of referencing the figure variable

Can you give a code example that work (e.g. using matplotlib only). That would be a great starting point for as I don't have to figure this out myself.

Thanks!

Best,
Robert

**Comment by somas193** [comment]
> Hi @somas193 ,
> 
> thanks for the report! I agree, we should fix this.
> 
> > instead of referencing the figure variable
> 
> Can you give a code example that works (e.g. using matplotlib only). That would be a great starting point for me as I don't have to figure this out myself.
> 
> Thanks!
> 
> Best, Robert

Hello @haesleinhuepf ,
I have written a small example code based on the parametric maps notebook on your website. 

`import numpy as np
import pyclesperanto_prototype as cle
from skimage.io import imread, imsave
from skimage.measure import regionprops, regionprops_table
from skimage.util import map_array
from napari_simpleitk_image_processing import label_statistics

binary = cle.artificial_objects_2d()
labels = cle.voronoi_otsu_labeling(binary, spot_sigma=5)

statistics_table = regionprops_table(cle.pull(labels), properties=('label', 'area',))
remapped = map_array(
        cle.pull(labels),
        statistics_table['label'],
        statistics_table['area'],
        )`

`# Normal subplots using the imshow() method-Doesn't work!
fig1, axs1 = plt.subplots(2, 3, figsize=(10,10))
cle.imshow(binary, plot=axs1[0,0])
cle.imshow(remapped, colorbar=True, color_map="jet", plot=axs1[0,1])
cle.imshow(binary, plot=axs1[0,2])
cle.imshow(binary, plot=axs1[1,0])
cle.imshow(remapped, colorbar=True, color_map="jet", plot=axs1[1,1])
cle.imshow(binary, plot=axs1[1,2])`

`# Subplots created using matplolib directly without scaling the colorbar
fig2, axs2 = plt.subplots(2, 3, figsize=(15,10))
im1 = axs2[0,0].imshow(binary, cmap='Greys_r')
im2 = axs2[0,1].imshow(remapped, cmap='jet')
fig.colorbar(im2, ax=axs2[0,1])
im3 = axs2[0,2].imshow(binary, cmap='Greys_r')
im4 = axs2[1,0].imshow(binary, cmap='Greys_r')
im5 = axs2[1,1].imshow(remapped, cmap='jet')
fig.colorbar(im5, ax=axs2[1,1])
im6 = axs2[1,2].imshow(binary, cmap='Greys_r')

plt.show()`
![no_scaling](https://user-images.githubusercontent.com/65766141/212978195-4cc85550-a579-4748-8e0d-5652a0f0bcd3.png)

`# Subplots created using matplolib directly with colorbar scaling
fig2, axs2 = plt.subplots(2, 3, figsize=(15,10))
im1 = axs2[0,0].imshow(binary, cmap='Greys_r')
im2 = axs2[0,1].imshow(remapped, cmap='jet')
cax = fig2.add_axes([axs2[0,1].get_position().x1+0.01, axs2[0,1].get_position().y0, 0.005, axs2[0,1].get_position().height])
fig.colorbar(im2, cax=cax)
im3 = axs2[0,2].imshow(binary, cmap='Greys_r')
im4 = axs2[1,0].imshow(binary, cmap='Greys_r')
im5 = axs2[1,1].imshow(remapped, cmap='jet')
cax2 = fig2.add_axes([axs2[1,1].get_position().x1+0.01, axs2[1,1].get_position().y0, 0.005, axs2[1,1].get_position().height])
fig.colorbar(im5, cax=cax2)
im6 = axs2[1,2].imshow(binary, cmap='Greys_r')

plt.show()`
![scaling](https://user-images.githubusercontent.com/65766141/212978248-a685d9ba-b863-4084-8b92-388864d79205.png)

**Comment by haesleinhuepf** [comment]
Hi @somas193 ,

just to let you know, with pyclesperanto_prototype 0.23.0 this should work now. I also added a demo notebook:
https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/demo/basics/imshow.ipynb

Thanks for your suggestion and special thanks for providing the code! I would have taken ages to figure that out. :-)

Best,
Robert

**Comment by somas193** [comment]
> Hi @somas193 ,
> 
> just to let you know, with pyclesperanto_prototype 0.23.0 this should work now. I also added a demo notebook: https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/demo/basics/imshow.ipynb
> 
> Thanks for your suggestion and special thanks for providing the code! I would have taken ages to figure that out. :-)
> 
> Best, Robert

That's great @haesleinhuepf ! I look forward to contributing more to the open source software ecosystem maintained by you :-)
