### ISSUE TITLE
cupy backend (experimental) AttributeError: module 'cupy' has no attribute '_core'

### ISSUE THREAD

**Issue by hamdaan-shaikh** [clEsperanto/pyclesperanto_prototype#250]
c:\Users\Hamdaan\anaconda3\envs\cle_39\lib\site-packages\cupyx\scipy\ndimage\interpolation.py:15: UserWarning: In the current feature the default order of affine_transform is 1. It is different from scipy.ndimage and can change in the future.
  warnings.warn('In the current feature the default order of {} is 1. '
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[10], line 6
      4     matrix, output_shape = scale_image(images[i])
      5     cupy_list.extend(cupy_affine(images[i], matrix, output_shape))
----> 6     clesperanto_list.extend(clesperanto_affine(images[i], matrix, output_shape))
      7 plot_comparison(cupy_list, clesperanto_list)

Cell In[8], line 3, in clesperanto_affine(image, matrix, output_shape)
      1 def clesperanto_affine(image, matrix, output_shape):
----> 3     ocl_image = cle.push(image)
      4     clesperantoImageAndAffineTransformTimeList = []
      6     no_of_calculations = 5

File c:\Users\Hamdaan\anaconda3\envs\cle_39\lib\site-packages\pyclesperanto_prototype\_tier0\_push.py:32, in push(any_array)
     28 if hasattr(any_array, "is_cuda") and any_array.is_cuda:
     29     # special treatment for pytorch tensors
     30     any_array = any_array.cpu()
---> 32 if isinstance(any_array, Backend.get_instance().get().array_type()):
     33     return any_array
     35 if isinstance(any_array, list) or isinstance(any_array, tuple):

File c:\Users\Hamdaan\anaconda3\envs\cle_39\lib\site-packages\pyclesperanto_prototype\_tier0\_cuda_backend.py:18, in CUDABackend.array_type(self)
     17 def array_type(self):
---> 18     return (CUDAArray, cupy._core.core.ndarray)

AttributeError: module 'cupy' has no attribute '_core'

**Comment by hamdaan-shaikh** [comment]
cupy.__version__ is 8.3.0

**Comment by haesleinhuepf** [comment]
Hi @hamdaan-shaikh ,

thanks for reporting this! I just checked: I'm using cupy version 11.4.0 and it works. I'm now wondering why your computer installed [cupy 8.3.0](https://github.com/cupy/cupy/releases/tag/v8.3.0) which is about two years old. Can you recall how you installed cupy?

Thanks again!

Best,
Robert

**Comment by hamdaan-shaikh** [comment]
Hi @haesleinhuepf ,

![image](https://user-images.githubusercontent.com/42545761/215332745-d4d89f63-8606-498e-a065-5fc8884018cf.png)

The cupy I used was the one that came pre-installed in the Anaconda clesperanto environment setup

I will see if I can update it and make it work.

Thanks for the insight,
Hamdaan

**Comment by haesleinhuepf** [comment]
No pressure. I typically install things according to their installation instructions, e.g. for cupy you find them here:

https://docs.cupy.dev/en/stable/install.html#install-cupy-from-conda-forge

**Comment by haesleinhuepf** [comment]
This was related to an outdated cupy version
