### ISSUE TITLE
x,y,z ?mix? in 3D Image Segmentation demo

### ISSUE THREAD

**Issue by ClementCaporal** [clEsperanto/pyclesperanto_prototype#266]
Hello, thank you for your work.

In case it is useful to report this, I cannot reproduce https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/demo/segmentation/Segmentation_3D.ipynb under **"Intensity and background correction"** without the x,y slice being cropped.

![image](https://user-images.githubusercontent.com/94049435/221583846-4626f5c5-0e88-455b-98b4-128fa6e655f9.png)

Solved by
`a_slice = cle.create([resampled.shape[1], resampled.shape[0]])` 
->
`a_slice = cle.create([resampled.shape[1], resampled.shape[2]])`

**Comment by haesleinhuepf** [comment]
Hi @ClementCaporal ,

thanks for the report! I think you are right, I have the suspion that the code should be indeed `cle.create([resampled.shape[1], resampled.shape[2]])`. But I'm not sure why my result looks different than yours. I just ran the notebook (with the code as it was) and my result looks like this:
 
![image](https://user-images.githubusercontent.com/12660498/221619391-ad12d464-d159-493d-9201-6b07a47d8bc9.png)

Why do your input images have a different size?

Thanks!

Best,
Robert
