### ISSUE TITLE
I think this link might be broken

### ISSUE THREAD

**Issue by paxcalpt** [clEsperanto/pyclesperanto_prototype#271]
https://github.com/clEsperanto/pyclesperanto_prototype/blob/006379e7302cc0f76a571b5cdf3fb3962c9461c9/docs/readme.md?plain=1#L26

<img width="1218" alt="image" src="https://user-images.githubusercontent.com/763757/221800281-6d2ca371-1b1c-4108-b2fe-a039f04cc8bc.png">

**Comment by haesleinhuepf** [comment]
Note to self: That's the right link:
https://biapol.github.io/blog/johannes_mueller/entry_sphinx/Readme.html

Need to fix.

Thanks for reporting @paxcalpt !
