### ISSUE TITLE
could not find documentation for contributors

### ISSUE THREAD

**Issue by thawn** [clEsperanto/pyclesperanto_prototype#275]
I am trying to run the tests with pytest. I am getting the following errors

```
FileNotFoundError: [Errno 2] No such file or directory: 'pyclesperanto_prototype/pyclesperanto_prototype/_tier1/../clij-opencl-kernels/kernels/maximum_y_projection_x.cl'
```

I know that this is because I did not clone the clij opencl kernels properly into the pyclesperanto_prototype repository. 

However, I forgot how to do that and could not find the documentation that explains this here.

**Comment by haesleinhuepf** [comment]
Hi Till @thawn ,

I just tried: Cloning the repository using [github desktop](https://desktop.github.com/) works seamlessly. I presume if you clone using the command line, you may have to use some submodule command, e.g. as explained [here](https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/How-to-clone-a-git-repository-with-submodules-init-and-update) or [here](https://stackoverflow.com/questions/3796927/how-do-i-git-clone-a-repo-including-its-submodules). Let me know what works for you and I'll put it in the documentation.

Thanks for reporting!

Best,
Robert

**Comment by thawn** [comment]
this worked for me (I included the initial clone for completeness).

```bash
git clone git@github.com:clEsperanto/pyclesperanto_prototype.git
cd pyclesperanto_prototype
git submodule init
git submodule update
```
