### ISSUE TITLE
np.flip overwrites clesperanto array with the content of the first element of the respective axis

### ISSUE THREAD

**Issue by thawn** [clEsperanto/pyclesperanto_prototype#294]
Hi Robert,

thanks for fixing the last bug so quickly. Here is another one ;-)

pyclesperanto_prototype version: 0.23.6

the title describes the problem and this notebook reproduces it:

https://gitlab.mn.tu-dresden.de/tkorten/clesperanto_bug_minimal_example/-/blob/main/minimal_example.ipynb

Cheers,

Till

**Comment by haesleinhuepf** [comment]
Good catch @thawn !

The issue is releated to `cle.range()`, it cannot deal with negative step size. That's why `cle_array[::-1]` has the above mentioned wrong output... I'm on it.

**Comment by haesleinhuepf** [comment]
Hi Till @thawn ,

I just fixed this and released [`pyclesperanto-prototype==0.24.0`](https://github.com/clEsperanto/pyclesperanto_prototype/releases/tag/0.24.0). Let me know if the issue persists!

Thanks for reporting!

Best,
Robert
