### ISSUE TITLE
package is not on conda-forge

### ISSUE THREAD

**Issue by thawn** [clEsperanto/pyclesperanto_prototype#298]
`mamba install pyclesperanto_prototype` returns the following:
```bash
Looking for: ['pyclesperanto_prototype']

conda-forge/osx-arm64                                       Using cache
conda-forge/noarch                                          Using cache

Pinned packages:
  - python 3.10.*


Encountered problems while solving:
  - nothing provides requested pyclesperanto_prototype
```
pip install pyclesperanto_prototype successfully installs version 0.24.0

**Comment by psobolewskiPhD** [comment]
I can't reproduce this with mambaforge on my arm64 macOS.
What is the full command or install state? I don't get:
```
Pinned packages:
  - python 3.10.*
 ```
But I am on 3.10:
`python                    3.10.9          h3ba56d0_0_cpython    conda-forge`

**Comment by psobolewskiPhD** [comment]
Oh, I see the issue.
The package is `pyclesperanto-prototype` with a dash not underscore.

**Comment by thawn** [comment]
@psobolewskiPhD thanks for spotting this rather stupid mistake 😊 that fixed it
