### ISSUE TITLE
Jupyter notebook Kernel crashes while using pyclesperanto in Ubuntu 22.04.2 on WSL2, Windows 11

### ISSUE THREAD

**Issue by somas193** [clEsperanto/pyclesperanto_prototype#317]
![pyclesperanto_error](https://github.com/clEsperanto/pyclesperanto_prototype/assets/65766141/4f433193-5fb1-49e4-892f-f6f387218a52)
I am trying to run the workflow: https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/demo/tribolium_morphometry/tribolium_morphometry2.ipynb through VS Code on a system with Ubuntu 22.04.2 (Kernel:5.15.90.1-microsoft-standard-WSL2) installed in WSL2 on Windows 11. Initially, I wasn't able to select the GPU even after installing ocl-icd-system. Then, I also installed pocl and this made it possible to select between CPU and GPU. Now I am able to select the device but the Kernel crashes when I try to use any method from pyclesperanto. The same workflow runs without any problem on the host Windows system. The details are given below:

pyclesperanto version: 0.24.1
ocl-icd version: 2.3.1 
ocl-icd-system version: 1.0.0
pocl version: 4.0
CPU: AMD Ryzen 9 5900X
GPU: NVIDIA RTX A6000
nvidia-smi version: 510.47.03, driver version: 511.65

Any suggestions on how I can solve this issue?

**Comment by somas193** [comment]
I was under the assumption that the GPU setup works fine because I was able to query `nvidia-smi` on WSL and the workflow ran on the GPU on the host system. But I suppose that's not the case! I followed the instructions provided on the link above and I'm able to run the workflow on WSL now. For future reference I did the following:
1. Download appropriate drivers from: https://www.nvidia.com/Download/index.aspx?lang=en-us and install them on the host system (Windows 11)
2. Install the appropriate driver on WSL from: https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=WSL-Ubuntu&target_version=2.0&target_type=deb_local through commands given on the website
3. Run `wsl.exe -d Ubuntu --shutdown + wsl.exe --terminate Ubuntu` on the host system and start WSL. The condition of the drivers can be checked by querying `nvidia-smi`.

Thanks for the help @thawn

**Comment by somas193** [comment]
@thawn @haesleinhuepf  while running the workflow: https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/demo/tribolium_morphometry/tribolium_morphometry2.ipynb on WSL2 clesperanto selects the GPU runtime through the pocl-cuda driver and not the installed cuda driver whereas on the host system i.e. Windows 11 it detects the installed CUDA driver. Is this defined behavior for clesperanto on Linux/WSL2? AFAIK pocl is supposed to be used for CPU right?

**Comment by thawn** [comment]
> on WSL2, clesperanto selects the GPU runtime through the pocl-cuda driver and not the installed CUDA driver

afaik, [pocl-cuda is supposed to use the GPU](http://portablecl.org/cuda-backend.html), although the performance may vary. Could you please check with nvidia-smi what the GPU load is, while you are running a pyclesperanto workflow? That way, you could tell if it is using the GPU or not.
