### ISSUE TITLE
Convert numpy array to OCLArray?

### ISSUE THREAD

**Issue by ajsc4** [clEsperanto/pyclesperanto_prototype#318]
Is it possible to convert a numpy array into the pyclesperanto OCLArray image type?

**Comment by haesleinhuepf** [comment]
Hi @ajsc4 ,

yes, using `cle.asarray(np_array)`. Furthermore, all functions in pyclesperanto consume both kinds of images, opencl-based and numpy.

Let me know if this answers your question.

Best,
Robert
