### ISSUE TITLE
Citing pyclesperanto?

### ISSUE THREAD

**Issue by ajsc4** [clEsperanto/pyclesperanto_prototype#319]
Is there a preferred way to cite clEsperanto/pyclesperanto?

**Comment by haesleinhuepf** [comment]
Hi @ajsc4 ,

you can cite it like this:

Robert Haase, Pradeep Rajasekhar, Talley Lambert, grahamross123, Juan Nunez-Iglesias, Lachie, Clement Caporal, Christophe Avenel, ENicolay, & Elissavet Sandaltzopoulou. (2023). clEsperanto/pyclesperanto_prototype: 0.24.1 (0.24.1). Zenodo. https://doi.org/10.5281/zenodo.7827755
