### ISSUE TITLE
Meet `MEM_OBJECT_ALLOCATION_FAILURE` with a large medical image 

### ISSUE THREAD

**Issue by xiachenrui** [clEsperanto/pyclesperanto_prototype#326]
Hi, all

I run `voronoi_labeling` function with a large medical image (20,000 x 30,000) with tthousands of cells, and raise `MEM_OBJECT_ALLOCATION_FAILURE` error. I am using 2080ti with 11GB memory. Is there any solutions? Should I tile the whole image into smaller parts?

```python
pyopencl._cl.MemoryError: clEnqueueNDRangeKernel failed: MEM_OBJECT_ALLOCATION_FAILURE
```
Best,
Rui

**Comment by xiachenrui** [comment]
By the way, my server has 8x 2080ti, could I use them to parallel.

**Comment by StRigaud** [comment]
Hi @xiachenrui 

currently, in the prototype, your data are stored in the GPU as `float`, that means that in memory your image take `~20000*30000*4 b = 2.4Gb`.

`voronoi_labeling` requires x4 or x5 times the memory size of the image you are trying to process. This brings you easily to `12Gb` of memory occupancy which hit your max GPU memory.

I would indeed suggest you to tile your image if the problematic does not require you to analyses the entire image in one shot, ... or to use a bigger GPU ....

> By the way, my server has 8x 2080ti, could I use them to parallel.

Not directly with `pyclesperanto` as we do not manage multi-device distribution. However you can still distribute your processing across GPU or HPC by relying on [dask](https://www.dask.org/) and by looking at the [demo example](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/demo/interoperability/dask.ipynb)

Hope that's help

**Comment by xiachenrui** [comment]
Thanks for your kind help! It is useful for me.
