### ISSUE TITLE
How to assign my Nvidia M2200 when having and internal Intel HD card as well

### ISSUE THREAD

**Issue by sebi06** [clEsperanto/pyclesperanto_prototype#41]
My Win10 has two graphics cards.

```python
import pyclesperanto_prototype as cle
print(cle.get_device().name)
```
gives me: Intel(R) HD Graphics 530

How do assign my GPU here? (hope this is not a stupid question)

**Comment by haesleinhuepf** [comment]
Hi @sebi06 ,

great question! I just set up the example code for that some days ago:
https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/demo/basics/select_GPU.py

Let me know if this works on your system!

Cheers,
Robert

**Comment by tlambert03** [comment]
also, if for some reason you can't guess the appropriate string to pass to `select_device`, a list of available device names can be shown:
```python
import pyclesperanto_prototype as cle

cle._tier0._pycl.filter_devices()

# or, only show actual dedicated GPUs:
cle._tier0._pycl.filter_devices(dev_type='gpu')
```

**Comment by sebi06** [comment]
Thx. Works as expected.
