### ISSUE TITLE
OCLArray and OCLImage

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto_prototype#54]
Hey Talley @tlambert03 ,

I was just [diving](https://github.com/clEsperanto/pyclesperanto_prototype/commit/075250c8391852acd53b5f8038efcd8eeea9473f) a bit into [your](https://github.com/clEsperanto/pyclesperanto_prototype/commit/7073f5f979686de76d6237ace0cab0f8b8e944bf#diff-4eaddb7a6b27bebf0d613f87c254325358688455359f5417d3aebd119972e753) cl.Image code. For affine transforms & friends it's crucial to have cl.Images supported. 
I think we considered refactoring that part earlier and I would have some time to do it in the next weeks. I just wanted to ask you about your opinion/suggestions. I think it makes sense to implement an OCLImage as counter part to [OCLArray](https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/pyclesperanto_prototype/_tier0/_pycl.py#L237). Do you agree? Furthermore, I was wondering if there might be things in OCLArray and future OCLImage that could be improved from your perspective. For example having numpy compatibility https://github.com/clEsperanto/pyclesperanto_prototype/issues/33 in mind.

Thanks for your thoughts and hints!

Cheers,
Robert

**Comment by tlambert03** [comment]
not sure what exactly you mean by "as a counter part" ... but if you mean to follow that same `_wrap_OCLArray` pattern, then I'm not sure.  I vaguely recall being not super fond of that pattern with OCLArray, but it's been a while and I need to remind myself.  It could be just the thing :joy: 
I do agree we want `Image` and `Array` to have very similar APIs, so my preliminary Image (and or the OCLArray) code will definitely need some modifications to unify them

I also agree we should maintain as much compatibility with the numpy API as possible (worth reviewing [numpy's dispatch mechanism](https://numpy.org/doc/stable/user/basics.dispatch.html#basics-dispatch)) ...

**Comment by haesleinhuepf** [comment]
> but if you mean to follow that same `_wrap_OCLArray` pattern, then I'm not sure.

An alternative would be implementing something like 'OCLArray.get_as_image : cl.Image'. I think that would allow efficient implementation of all the aspects I would need the cl.Images for....

**Comment by tlambert03** [comment]
I'd say at this point, go with whatever you need to get the job done.  then we can refactor later as the "needs" become more obvious

**Comment by jni** [comment]
What's the discussion about here? What extra attributes does Image have that Array lacks?

I think the API we want to target is not NumPy, which is enormous and contains quite a lot of functionality there only for historical reasons, but rather the new data-apis Array API:

https://data-apis.github.io/array-api/latest/API_specification/array_object.html

**Comment by haesleinhuepf** [comment]
> What's the discussion about here? What extra attributes does Image have that Array lacks?

Images and Arrays are defined on OpenCL level. We typically use arrays. For images, there is some kind of hardware optimization (!) to access neighboring pixels and for linear interpolation. For arrays we have a convenience layer/wrapper (OCLArray) and I was wondering if we should have that as well for Images. It's not necessary but would simplify acceess/usage of them.

Thanks to the links! I'll take a closer look. 🙂
