### ISSUE TITLE
ImportError: DLL load failed while importing _cl: The specified procedure could not be found.

### ISSUE THREAD

**Issue by JulesScholler** [clEsperanto/pyclesperanto_prototype#55]
I got this error when trying to use Clesperanto on a workstation. I created the conda env by generating a environment.yml from my laptop where CLE works great. I tried installing pyopencl 2020.1 as indicated but still got the error.

**Comment by haesleinhuepf** [comment]
Hi @JulesScholler ,

the error message looks similar the one in the [trouble shooting section here](https://github.com/clEsperanto/pyclesperanto_prototype). This happens when you installed pyopencl version "cl21" for using a GPU that only supports OpenCL 1.2 (that's true for many NVidia cards). Try installing a different pyopencl with version "cl12".

Let us know if this helps!

Cheers,
Robert

**Comment by JulesScholler** [comment]
Sorry for my silly issue I focussed on 2020.1 (now it's 2020.3) rather than cl 12 (as opposed to cl21). With OpenCL 1.2 it works like a charm! Thanks @haesleinhuepf

**Comment by CamachoDejay** [comment]
Hi @haesleinhuepf ,
I am having the sample problem here on my Windows server. After a fresh installation of the napari plugin following the instructions here-> https://github.com/clesperanto/napari_pyclesperanto_assistant I get the error message:
"ImportError: DLL load failed while importing _cl: The specified procedure could not be found."
Could you help me troubleshoot

**Comment by haesleinhuepf** [comment]
Hi Rafa @CamachoDejay ,

can you please try to update your GPU driver? I assume you're working with an NVidia card?
https://www.nvidia.com/download/index.aspx

Let me know if this helps!

Best,
Robert

**Comment by CamachoDejay** [comment]
Hej Robert @haesleinhuepf,
The update fixed the issue. Thanks for the advice.

Saludos,
Rafa

**Comment by Daniel-Waiger** [comment]
HI @haesleinhuepf,

I have a Quadro A4000, but it's not detected.
I updated my driver to the latest version.

I don't see a reference to this behavior, and how to change it.
`import pyclesperanto_prototype as cle

cle.get_device()`

`<Intel(R) UHD Graphics 630 on Platform: Intel(R) OpenCL HD Graphics (1 refs)>`

How can I change the selected card?

Thanks,
Daniel
