### ISSUE TITLE
Use pytest as testing framework

### ISSUE THREAD

**Issue by jni** [clEsperanto/pyclesperanto_prototype#6]
In #2, the "tests" are a file to be run with Python. [pytest](https://docs.pytest.org/en/latest/) provides a lot of nice features like running *all* test files, specifying which tests exactly are failing, and much more. To do so, tests should be placed in files called `test_something.py`, and within each file, each test should be its own function, `def test_something_specific():`, which can have assertions etc within it.

**Comment by haesleinhuepf** [comment]
Just adding this link from our earlier discussion:
https://ilovesymposia.com/2014/10/01/continuous-integration-0-automated-tests-with-pytest/
:-)
