### ISSUE TITLE
installing pyopencl windows

### ISSUE THREAD

**Issue by tlambert03** [clEsperanto/pyclesperanto_prototype#82]
just curious, have you tried using any of the pre-compiled pyopencl on [conda forge](https://anaconda.org/conda-forge/pyopencl/files)?  I can't immediately tell from [the recipe](https://github.com/conda-forge/pyopencl-feedstock/blob/master/recipe/meta.yaml) which version of opencl they are compiled against.  But they do tend to work for me on Nvidia devices on windows and might be an easier method to suggest in your readme (unless, of course, you've already tried them and decided against it! :)

`conda install -c conda-forge pyopencl=2019.1.2`

**Comment by haesleinhuepf** [comment]
Great idea Talley @tlambert03 . I haven't tried for a while. And I'm basically only using pip these days. 

I just tried again:
```
pip uninstall pyopencl

conda install -c conda-forge pyopencl=2020.3.1
```

And then this code:
```
```

causes this error:
```
```

**Comment by tlambert03** [comment]
yeah, that'll be an issue for sure, it didn't install! :)  not sure, but it's always possible when you pip uninstall something and then conda install something, that the two package managers confuse each other.  So just to be sure, try it out in a new environment where you haven't already pip installed your manually downloaded pyopnecl

**Comment by haesleinhuepf** [comment]
IT WORKS! On a freshly installed windows pc. Wow, thanks!

So I'll add that way for installing it to the readme. How can we use this info for packaging the napari-plugin correctly?

**Comment by tlambert03** [comment]
Well, unfortunately you can’t declare conda dependencies in pip, so this would basically just stay as a recommendation in your readme, _or_ you can create your own conda package and have it be the recommended way to install (which a lot of platform-specific binary heavy packages do), in which case you can specify other conda dependencies and then you’d be all good.  (All of the Cuda stuff I’ve distributed in the past has only been available via conda).

**Comment by tlambert03** [comment]
(Not to say that you should remove it from pypi, just offer conda ask well for windows users specifically)

**Comment by haesleinhuepf** [comment]
Alright. Thanks again, for the really good hint. I hope we can solve the windows installation more substanially one day.
