### ISSUE TITLE
Build a user interface prototype for clesperanto

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto_prototype#9]
Hey @pr4deepr ,

I know you're looking for a challange to get started with clesperanto. And I know you're at least as fascinated about napari as I am. You know that the major benefit of GPU-acceleration is real-time response when processing images. So how about building a user interface for napari where the user can configure some filters - in real time ;-)

Cedric Espenel (@bioimage-analysis) did something similar and showed in on twitter:
https://twitter.com/CEspenel/status/1265028814620385281?s=20
![image](https://user-images.githubusercontent.com/12660498/83731254-7f321200-a64a-11ea-9d16-3eb546f03f17.png)

And he put the code online. 
https://gist.github.com/bioimage-analysis/fd720f98495d53e5c5ff4eb431f6acb0

As you can see, there are tabs in this napari-based user interface offering different filters. Using a GPU, one could pre-compute all filters at a time and/or filters with different settings to give the user an impression of what they are configuring with sigma, radius, ... ;-) Furthermore, one could configure complex workflows in such a user interface. I showed that at some point in Fiji:
![image](https://user-images.githubusercontent.com/12660498/83731770-5b230080-a64b-11ea-9fdc-289b6c40d8c6.png)
https://twitter.com/haesleinhuepf/status/1196468240274350080?s=20

At the end I'd love to make something like this, but don't know if napari has the necesssary callback infrastructure available already:
https://twitter.com/haesleinhuepf/status/1264922487831363584?s=20
![image](https://user-images.githubusercontent.com/12660498/83731343-a1c42b00-a64a-11ea-975e-6cd69c224eb5.png)

Let me know if you find this as interesting as I do. If not, don't worry. I'm pretty sure this will come to napari at some point, GPU-accelerated or not ;-)

Cheers,
Robert

**Comment by pr4deepr** [comment]
This looks good, am happy to give this a go!!!

**Comment by pr4deepr** [comment]
@haesleinhuepf 
I've given this a go using [magicgui ](https://magicgui.readthedocs.io/en/latest/) as a start. You can find the code here:
https://github.com/pr4deepr/pyclesperanto_prototype/blob/master/napari_clij_widget.py

Gif with the napari interface
![Napari gif](https://github.com/pr4deepr/pyclesperanto_prototype/blob/master/clij%20napari%20widget.gif)
In case, this doesnt work, screenshot:
![image](https://user-images.githubusercontent.com/13831458/85822429-26bfe180-b7be-11ea-99ac-eb0dc91a65f1.png)
![image](https://user-images.githubusercontent.com/13831458/85822455-39d2b180-b7be-11ea-8ed6-a29e3116e9aa.png)

3D Gaussian blur is giving weird results:
![image](https://user-images.githubusercontent.com/13831458/85822946-81a60880-b7bf-11ea-8225-abb105b4936f.png)

2D seems to be ok:
![image](https://user-images.githubusercontent.com/13831458/85823223-39d3b100-b7c0-11ea-8966-788e1c4905bc.png)

The code definitely needs a lot of work. 
I used [magicgui](https://magicgui.readthedocs.io/en/latest/)
Just like the magicgui examples, I am using enums for generating lists. I tried passing clesperanto functions as a value, but it was not working. So, I had to make them strings,pass them as a string to the function, concatenate strings and used exec() operation to parse the string and execute the command:

```
 output = cle.create_like(input.data)
 # concatenate the value from gpu_operation  as a string
 command = operation.value + "(cle_input, output, x, y, z)"
 # use evaluate to execute the command
 eval(command)
```

It works, but definitely a hack more than anything and its not pretty. I would like to know why I can't pass clesperanto plugins/functions as values. @jni may have some good answers here.. Don't puke... haha

**Comment by haesleinhuepf** [comment]
Hey @pr4deepr ,

awesome work! 🤩 I love it. I've fixed some little things in your code and sent a pull-request. The only bug which is left is the Gaussian-blur thingy. Will dive into this asap.

Also magicgui is obiously awesome. I activated the auto-call and thus, it's the very first time in my life, that I can change parameters and look at changes in a 3D viewer:
![napari_cle_29-06-2020-21-22-15](https://user-images.githubusercontent.com/12660498/86047508-43bf1380-ba4f-11ea-86b3-1c20161a9338.gif)

Thanks for paving this path!

Cheers,
Robert

**Comment by haesleinhuepf** [comment]
PS: In case the video is not playing:
[napari_cle_29-06-2020-21-22-15.zip](https://github.com/clEsperanto/pyclesperanto_prototype/files/4847632/napari_cle_29-06-2020-21-22-15.zip)

**Comment by pr4deepr** [comment]
Hi @haesleinhuepf 
I tried a different approach. I wanted to list all the filters without manually typing it in..
I got a list of packages in the clesperanto plugins folder and passed them into a list ([pkgutil.walk_packages](https://docs.python.org/3/library/pkgutil.html)). I've used operation [methodcaller](https://docs.python.org/3.2/library/operator.html) here. 

Again, if this is not a good approach, do let me know. 

![clij_widget_list](https://user-images.githubusercontent.com/13831458/86446369-33f94500-bd57-11ea-952e-9dee0912287a.gif)

The code is [here](https://github.com/pr4deepr/pyclesperanto_prototype/blob/master/napari_clesperanto_widget_list.py)

It throws errors when using power or mask as it expects different arguments. Again, if this is not a good approach, like using eval, please do let me know. 

I am also having a look at PyQt and trying to generate a custom interface like you specified initially. Almost got the hang of it..

**Comment by haesleinhuepf** [comment]
OMG @pr4deepr! You are crazy 😉 Feel free to tweet videos like this 🤩  A bit PR never hurts 😉

**Comment by pr4deepr** [comment]
Glad you like it.. Its not perfect of course....
I gave it a try on a 1456x1456x92 image: around 372 MB... 
You'll like this:
![clij_widget_list_big image](https://user-images.githubusercontent.com/13831458/86450521-06af9580-bd5d-11ea-9a2d-8df22518e3f6.gif)
BTW, its an image of neurons from the gut wall...

**Comment by haesleinhuepf** [comment]
Beautiful! 🤩  Btw, looking a the task manager: It's hard to get the GPU busy (but doable). Image Processing is memory bound and not so much computing intensive. Could be worse: If it would be the other way around, we would hear the fan of our GPUs all the time ;-)

**Comment by pr4deepr** [comment]
@haesleinhuepf @jni 
I have tried addressing the problem of using enum where it wouldn't return a function as its value,
 by using functools.partial:
```
class gpu_filter(Enum):
    # using pyclesperanto filtering images with a gpu
    #using functools.partial to return functions as enum values:
    #https://stackoverflow.com/questions/40338652/how-to-define-enum-values-that-are-functions
    mean = partial(cle.minimum_sphere)
    maximum = partial(cle.maximum_sphere)
    minimum = partial(cle.minimum_sphere)
    top_hat = partial(cle.top_hat_sphere)
    gaussian_blur = partial(cle.gaussian_blur)
    crop = partial(cle.crop)

    #define the call method for the functions or it won't return anything
    def __call__(self, *args):
        return self.value(*args)
```
Changes are [here](https://github.com/pr4deepr/pyclesperanto_prototype/blob/62ad770a7896872affc2c81d5864bca057abdb5b/napari_clij_widget.py#L18)
