### ISSUE TITLE
Use inspect.signature instead of getfullargspec

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/pyclesperanto_prototype#94]
Use `inspect.signature` instead of `getfullargspec` as it's the more recent API.

Affected files:
https://github.com/clEsperanto/pyclesperanto_prototype/blob/master/pyclesperanto_prototype/_tier0/_plugin_function.py

Also in related project:
https://github.com/clEsperanto/napari_pyclesperanto_assistant/blob/master/napari_pyclesperanto_assistant/_scriptgenerators/_JythonGenerator.py#L48

**Comment by jni** [comment]
Closed by #95
